import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Why: 외부 FE 독자를 위한 선형 여정(구현이란 → 설계 → 구현 → 검증 → 개선 → 태도)
// 을 3 테마 × 2 파일로 배치. autogenerated가 아닌 명시 구성이라 앞으로 docs/ 아래에
// 새 디렉토리가 생겨도 이 파일을 고쳐야만 사이드바에 노출된다. appendix(내부 대시보드)는
// 의도적으로 제외 — URL(/appendix/dashboard)은 살아있되 사이드바에서는 감춤.
const sidebars: SidebarsConfig = {
  bookSidebar: [
    'index',
    {
      type: 'category',
      label: '🧭 구현의 기초',
      collapsed: false,
      items: ['foundations/construction', 'foundations/design'],
    },
    {
      type: 'category',
      label: '✏️ 좋은 코드 쓰기',
      collapsed: false,
      items: ['good-code/routines', 'good-code/quality'],
    },
    {
      type: 'category',
      label: '🔧 완성과 성장',
      collapsed: false,
      items: ['growth/refactoring', 'growth/craftsmanship'],
    },
  ],
};

export default sidebars;
