import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Why: autogenerated 방식은 docs/ 아래 모든 디렉토리를 사이드바에 자동 노출한다.
// appendix(내부 집계 대시보드)는 URL로는 접근 가능하되 외부 독자의 사이드바에는
// 노출하지 않고 싶어서 명시적(explicit) 구성으로 전환. dashboard.mdx 자체는 빌드에
// 포함되므로 /appendix/dashboard URL은 살아있다. 내부 팀원만 URL을 알고 들어간다.
const sidebars: SidebarsConfig = {
  bookSidebar: [
    'index',
    {
      type: 'category',
      label: '스터디 노트',
      collapsed: false,
      items: [
        'weeks/week-02',
        'weeks/week-03-04',
        'weeks/week-05',
        'weeks/week-06',
        'weeks/week-07',
        'weeks/week-08',
      ],
    },
  ],
};

export default sidebars;
